### ISSUE TITLE
When will the training code be released?

### ISSUE THREAD

**Issue by hannajiang** [RongchangLi/ZSCAR_C2C#2]
Thank you for your excellent work. When will the training code be uploaded?

**Comment by RongchangLi** [comment]
> Thank you for your excellent work. When will the training code be uploaded?

Thank you for your interest. Codes will be released in one week.

**Comment by RongchangLi** [comment]
> Thank you for your excellent work. When will the training code be uploaded?

The code for training and testing models in the VM+word embedding paradigm has been uploaded. Please feel free to contact me if you encounter any issues during data preparation or reproducing the results.
