### ISSUE TITLE
code

### ISSUE THREAD

**Issue by hannajiang** [RongchangLi/ZSCAR_C2C#5]
Will you still release the training codes from VLM paradigm?

**Comment by RongchangLi** [comment]
> Will you still release the training codes from VLM paradigm?

Yes. I will release the code in 10 days.

**Comment by hannajiang** [comment]
hello, How much memory does the VLM paradigm code require? When will you release it?

**Comment by RongchangLi** [comment]
> hello, How much memory does the VLM paradigm code require? When will you release it?

Hello, it requires less than  40GB GPU memory. There are some problems causing the delay and I am sorry for it. The code will be released before this Friday.

**Comment by RongchangLi** [comment]
> hello, How much memory does the VLM paradigm code require? When will you release it?

Hello, the vlm codes have been released. Please let me know if there are any problems.
