### ISSUE TITLE
The process of loading the dataset is very slow

### ISSUE THREAD

**Issue by Yxt1212** [RongchangLi/ZSCAR_C2C#6]
Great work, thanks for open sourcing. I have a problem. When the model is just starting to train, the process of loading the dataset is very slow, which makes it difficult to debug the code and reproduce the results. Is there a good solution?

**Comment by jh-yi** [comment]
The same problem here. 
My monkey-patching atm.: 
self.data = self.data[:100]
in CompositionVideoDataset/__init__() if I'm debugging.

**Comment by Yxt1212** [comment]
> The same problem here. My monkey-patching atm.: self.data = self.data[:100] in CompositionVideoDataset/**init**() if I'm debugging.

Good！

**Comment by RongchangLi** [comment]
Hello, @Yxt1212, @jh-yi, sorry for late replying.  I didn't encounter a similar problem. Could you check if the data is stored on a device that allows fast reading (for example, SSD?

**Comment by jh-yi** [comment]
> Hello, @Yxt1212, @jh-yi, sorry for late replying. I didn't encounter a similar problem. Could you check if the data is stored on a device that allows fast reading (for example, SSD?

Thanks a lot for your information. It's indeed faster (<4s, previously >1000s) now after moving data to local SSD.
